services:
  - type: web
    name: customspyfall
    env: node
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
